# Generated by Django 5.2.8 on 2025-12-10 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário'), ('pix', 'PIX')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=47, unique=True)),
                ('linha_digitavel', models.CharField(max_length=54, unique=True)),
                ('numero_boleto', models.CharField(max_length=20, unique=True)),
                ('banco', models.CharField(default='Banco do Brasil', max_length=50)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('emitido', 'Emitido'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='emitido', max_length=20)),
                ('pdf_arquivo', models.FileField(blank=True, null=True, upload_to='boletos/')),
                ('pagador_nome', models.CharField(max_length=255)),
                ('pagador_cpf_cnpj', models.CharField(max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='orders.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='PixPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.TextField()),
                ('chave_pix', models.CharField(help_text='Chave PIX (CPF, email, telefone ou aleatória)', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('transacao_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix', to='orders.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Pagamento PIX',
                'verbose_name_plural': 'Pagamentos PIX',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
