# Generated by Django 5.2.8 on 2025-11-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_produto_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='em_destaque',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
