# Generated by Django 5.2.8 on 2025-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário (máx 5MB)', null=True, upload_to='perfil/'),
        ),
    ]
